[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../ast" }
env_logger = "0.11.3"
log = "0.4.21"
pest = "2.7.9"
pest_derive = "2.7.9"
thiserror = "1.0.61"
